var express = require('express');
var router = express.Router();
const Controller = require("../controller/smssender");
router.post("/", Controller.create);
router.get("/", Controller.list);
router.get("/:id", Controller.edit);
router.put("/:id", Controller.update);
router.delete("/:id", Controller.delete);
// router.post('/send', Controller.sendEmail);
module.exports = router;