services:
  - type: static
    name: housecare-frontend
    env: static
    root: Housecare        # or remove this and use repo root patterns
    installCommand: npm install --legacy-peer-deps
    buildCommand: npm run build
    publishPath: build
